language: objective-c
osx_image: xcode8

env:
- ACTION=build  PLATFORM=macOS  SCHEME='EasyPreference macOS'   DESTINATION='platform=OS X'
- ACTION=build  PLATFORM=iOS     SCHEME='EasyPreference iOS'     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
- ACTION=build  PLATFORM=tvOS    SCHEME='EasyPreference tvOS'    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
- ACTION=build  PLATFORM=watchOS SCHEME='EasyPreference watchOS' DESTINATION='platform=watchOS Simulator,name=Apple Watch - 42mm'

script:
- set -o pipefail && xcodebuild -workspace EasyPreference.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" $ACTION | xcpretty
